# This is a basic workflow to help you get started with Actions

name: Openfaas CIDI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - uses: actions/checkout@v1 # This is a dependency of the action 
    - name: OpenFaaS build and push
      uses: mrsimpson/action-openfaas-build@0.3.0
      with:
      # Your docker username with push authorization
         docker-username: ${{ secrets.d_u }}
      # Your docker password
         docker-password: ${{ secrets.d_p }}
      # the platform abbreviations to build for, e. g. linux/amd64,linux/arm/v7
         platforms: linux/amd64
      # Whether the built image shall be deployed (false=no, true=yes)
         deploy: true
      # OpenFaaS gateway URL (http(s)://my-public-gateway.tld)
         openfaas-gateway: ${{ secrets.faas_g }}
      # User for authenticating at OpenFaaS gateway
         openfaas-username: ${{ secrets.faas_u }}
      # Password for authenticating at OpenFaaS gateway
         openfaas-password: ${{ secrets.faas_p }}
